---
title: "ATC Concept Class Graph"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ATC Concept Class Graph}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(chariotViz)
library(tidyverse)

atc_rel <-
  fetch_omop("ATC", 
             "RxNorm",
             version_key = get_version_key())
atc_ne <- 
  create_nodes_and_edges(omop_relationships = atc_rel)
atc_ne <- 
  add_tooltip(atc_ne)
atc_ne <- 
  map_node_attributes(atc_ne,
                      fontsize = 34)
atc_ne <- 
  map_edge_attributes(atc_ne)
atc_graph <- 
  construct_graph(atc_ne)
```


```{r}
library(DiagrammeR)
atc_graph@graph %>% 
  select_nodes(
    conditions = vocabulary_id %in% c("ATC")) %>%
  select_nodes(
    conditions = vocabulary_id %in% c("RxNorm"),
    set_op = "union") %>%
  transform_to_subgraph_ws() %>%
  render_graph(width = 1500,
               height = 1500)


atc_graph@graph %>% 
  select_nodes(
    conditions = vocabulary_id %in% c("RxNorm")) %>%
  select_nodes(
    conditions = vocabulary_id %in% c("RxNorm"),
    set_op = "union") %>%
  transform_to_subgraph_ws() %>%
  render_graph(width = 1500,
               height = 1500)
```

