---
title: "Getting Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache.path = file.path(R.cache::getCachePath(),
                         "chariotViz",
                         "vignettes")
)
```

```{r setup}
library(chariotViz)
```

```{r}
omop_relationships <- 
  fetch_omop("SNOMED", 
             version_key = get_version_key())
omop_relationships
```

```{r}
omop_nodes_and_edges <- 
  create_nodes_and_edges(omop_relationships = omop_relationships)
```


```{r}
omop_nodes_and_edges <- 
  omop_nodes_and_edges %>% 
  add_tooltip()
```


```{r}
omop_nodes_and_edges <- 
  omop_nodes_and_edges %>%
  map_node_attributes()
```

```{r}
omop_nodes_and_edges <- 
  omop_nodes_and_edges %>% 
  map_edge_attributes()
```

```{r}
snomed_graph <- 
  construct_graph(omop_nodes_and_edges)
```

```{r}
library(DiagrammeR)
```

```{r}
snomed_graph@graph %>% 
  count_nodes()

snomed_graph@graph %>% 
  count_edges()
```


```{r}
snomed_graph2 <- 
snomed_graph@graph %>% 
  select_nodes(concept_class_id == "Qualifier Value") %>%
  transform_to_subgraph_ws() 


snomed_graph2 %>% 
  count_nodes()

snomed_graph2 %>% 
  count_edges()


snomed_graph2 %>%
  render_graph(width = 250,
               height = 1000)
```

```{r}
snomed_graph3 <- 
snomed_graph@graph %>% 
  select_nodes(concept_class_id == "Qualifier Value") %>%
  select_nodes(vocabulary_id == "SNOMED", set_op = "intersect") %>%
  transform_to_subgraph_ws() 


snomed_graph3 %>% 
  count_nodes()


snomed_graph3 %>% 
  count_edges()

snomed_graph3 %>%
  render_graph(width = 250, 
               height = 1000)
```

```{r}
snomed_graph4 <- 
snomed_graph@graph %>% 
  select_nodes(concept_class_id == "Qualifier Value") %>%
  select_nodes(vocabulary_id == "SNOMED", set_op = "intersect") %>%
  trav_out() %>%
  transform_to_subgraph_ws() 


snomed_graph4 %>% 
  count_nodes()


snomed_graph4 %>% 
  count_edges()
```

```{r}
snomed_graph5 <- 
snomed_graph@graph %>% 
  select_nodes(concept_class_id == "Qualifier Value") %>%
  select_nodes(vocabulary_id == "SNOMED", set_op = "intersect") %>%
  select_nodes(vocabulary_id == "RxNorm", set_op = "union") %>%
  subgraph(src = snomed_graph@src)


snomed_graph5@graph %>% 
  count_nodes()


snomed_graph5@graph %>% 
  count_edges()

chariotViz(snomed_graph5)
```


```{r}
snomed_graph6 <- 
snomed_graph@graph %>% 
  select_edges(
    from = 
    snomed_graph@graph %>% 
    select_nodes(concept_class_id == "Qualifier Value") %>%
    select_nodes(vocabulary_id == "SNOMED", set_op = "intersect") %>%
    get_selection()) %>% 
  select_edges(
    to = 
        snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "RxNorm", set_op = "union") %>%
    get_selection(),
    set_op = "intersect") %>%
  subgraph(src = snomed_graph@src)


snomed_graph6@graph %>% 
  count_nodes()


snomed_graph6@graph %>% 
  count_edges()

chariotViz(snomed_graph6)
```

```{r}
snomed_graph7 <- 
snomed_graph@graph %>% 
  select_edges(
    from = 
    snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    get_selection()) %>% 
  select_edges(
    to = 
        snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "RxNorm") %>%
    get_selection(),
    set_op = "intersect") %>%
  subgraph(src = snomed_graph@src)


snomed_graph7@graph %>% 
  count_nodes()


snomed_graph7@graph %>% 
  count_edges()

chariotViz(snomed_graph7)
```

```{r}
snomed_graph8 <- 
snomed_graph@graph %>% 
  select_edges(
    from = 
    snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    get_selection()) %>% 
  select_edges(
    to = 
        snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    get_selection(),
    set_op = "intersect") %>%
  subgraph(src = snomed_graph@src)


snomed_graph8@graph %>% 
  count_nodes()


snomed_graph8@graph %>% 
  count_edges()

chariotViz(snomed_graph8)
```


```{r}
snomed_graph8 <- 
snomed_graph@graph %>% 
  select_edges(
    from = 
    snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    select_nodes(concept_class_id == "Clinical Drug",
                 set_op = "intersect") %>%
    get_selection()) %>% 
  select_edges(
    to = 
        snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    get_selection(),
    set_op = "intersect") %>%
  subgraph(src = snomed_graph@src)


snomed_graph8@graph %>% 
  count_nodes()


snomed_graph8@graph %>% 
  count_edges()

chariotViz(snomed_graph8)
```


```{r}
snomed_graph8 <- 
snomed_graph@graph %>% 
  select_edges(
    from = 
    snomed_graph@graph %>% 
    select_nodes(vocabulary_id == "SNOMED") %>%
    select_nodes(concept_class_id == "Clinical Drug",
                 set_op = "intersect") %>%
    get_selection()) %>% 
  select_edges(
    to = 
        snomed_graph@graph %>% 
    select_nodes(vocabulary_id != "SNOMED") %>%
    get_selection(),
    set_op = "intersect") %>%
  subgraph(src = snomed_graph@src)


snomed_graph8@graph %>% 
  count_nodes()


snomed_graph8@graph %>% 
  count_edges()

chariotViz(snomed_graph8)
```


```{r}
snomed_graph8 <- 
snomed_graph@graph %>% 
  select_edges(
    from = filter_node_id_1(snomed_graph,
                            vocabulary_id_1 == "SNOMED",
                             concept_class_id_1 == "Qualifier Value"),
    to  = filter_node_id_2(snomed_graph, 
                           !(vocabulary_id_2 %in% "SNOMED"),
                           concept_class_id_2 != "Qualifier Value")) %>%
  subgraph(src = snomed_graph@src)


chariotViz(snomed_graph8)
```

```{r}
from_counts <- view_from_counts(snomed_graph8)
from_counts
```

```{r}
to_counts <- view_to_counts(snomed_graph8)
to_counts
```
