---
title: "RxNorm and RxNorm Extension"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RxNorm and RxNorm Extension}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  error   = FALSE,
  cache.path = file.path(R.cache::getCachePath(),
                         "chariotViz",
                         "vignettes"),
  cache = TRUE
)
```

**Last Update On**: `r as.character(Sys.time())`  

```{r,echo=F,eval=TRUE,results='hide',message=F,warning=F}
library(chariotViz)
version_key <- 
  get_version_key()
```

```{r,echo=F,eval=TRUE,message=F,warning=F}
rmd_print_version(version_key, 
                  "RxNorm",
                  "RxNorm Extension")
```


```{r setup}
library(chariotViz)
library(tidyverse)
```

```{r,cache=T}
omop_relationships <- 
  fetch_omop_relationships(
    "RxNorm",
    "RxNorm Extension",
    version_key = get_version_key())
```

```{r}
omop_nodes_and_edges <- 
  create_nodes_and_edges(omop_relationships = omop_relationships)
```


```{r}
omop_nodes_and_edges <- 
  omop_nodes_and_edges %>% 
  add_tooltip() %>%
  map_node_attributes() %>% 
  map_edge_attributes()
```

```{r}
omop_graph <- 
  construct_graph(omop_nodes_and_edges)
```


```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm Extension")) %>% 
    slot(name = "data"),
    omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm Extension"),
      vocabulary_id_2 %in% c("RxNorm")) %>%
    slot(name = "data")) %>%
  distinct() %>% 
  arrange(vocabulary_id_1, 
          vocabulary_id_2)
```

```{r}
rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           force = TRUE,
           width = 2000,
           height = 2000)
```

```{r}
rxnorm_graph@graph$edges_df %>% 
  count(vocabulary_id_1,
        vocabulary_id_2,
        relationship_source,
        sort = TRUE)
```

```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm Extension")) %>% 
    slot(name = "data")) %>%
  distinct() %>% 
  arrange(vocabulary_id_1, 
          vocabulary_id_2)

rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           force = TRUE,
           width = 500,
           height = 2500)
```


```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm")) %>% 
    slot(name = "data")) %>%
  distinct() %>% 
  group_by(concept_class_id_1,
           standard_concept_1) %>% 
  mutate(count_1 = n()) %>% 
  ungroup() %>% 
  group_by(concept_class_id_2,
           standard_concept_2) %>% 
  mutate(count_2 = n()) %>% 
  ungroup() %>%
  arrange(desc(count_1),
          desc(count_2)) %>% 
  select(-count_1,
         -count_2)

rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           width = 2500,
           height = 2500)
```


```{r}
rxnorm_graph2 <- 
  rxnorm_graph %>% 
  remap_fillcolor_by_concept_class()

chariotViz(rxnorm_graph2,
           width = 2500,
           height = 2000)
```


```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm")) %>% 
    slot(name = "data")) %>%
  distinct() %>% 
  group_by(concept_class_id_1,
           standard_concept_1) %>% 
  mutate(count_1 = n()) %>% 
  ungroup() %>% 
  group_by(concept_class_id_2,
           standard_concept_2) %>% 
  mutate(count_2 = n()) %>% 
  ungroup() %>%
  arrange(desc(count_1),
          desc(count_2)) %>% 
  select(-count_1,
         -count_2) %>% 
  dplyr::filter(relationship_source == "RxNorm"|is.na(relationship_source))

rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           width = 2500,
           height = 2500)
```


```{r}
rxnorm_graph2 <- 
  rxnorm_graph %>% 
  remap_fillcolor_by_concept_class()

chariotViz(rxnorm_graph2,
           width = 2500,
           height = 2000)
```

```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm")) %>% 
    slot(name = "data")) %>%
  distinct() %>% 
  group_by(concept_class_id_1,
           standard_concept_1) %>% 
  mutate(count_1 = n()) %>% 
  ungroup() %>% 
  group_by(concept_class_id_2,
           standard_concept_2) %>% 
  mutate(count_2 = n()) %>% 
  ungroup() %>%
  arrange(desc(count_1),
          desc(count_2)) %>% 
  select(-count_1,
         -count_2) %>% 
  dplyr::filter(relationship_source == "OMOP"|is.na(relationship_source))

rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           width = 1000,
           height = 1000)
```


```{r}
rxnorm_graph2 <- 
  rxnorm_graph %>% 
  remap_fillcolor_by_concept_class()

chariotViz(rxnorm_graph2,
           width = 1000,
           height = 1000)
```


```{r}
rxnorm_relationships <- omop_relationships
rxnorm_relationships@data <- 
  bind_rows(
  omop_relationships %>% 
    filter_omop_relationships(
      vocabulary_id_1 %in% c("RxNorm"),
      vocabulary_id_2 %in% c("RxNorm")) %>% 
    slot(name = "data")) %>%
  distinct() %>% 
  group_by(concept_class_id_1,
           standard_concept_1) %>% 
  mutate(count_1 = n()) %>% 
  ungroup() %>% 
  group_by(concept_class_id_2,
           standard_concept_2) %>% 
  mutate(count_2 = n()) %>% 
  ungroup() %>%
  arrange(desc(count_1),
          desc(count_2)) %>% 
  select(-count_1,
         -count_2) %>% 
  dplyr::filter(is.na(relationship_source))

rxnorm_graph <- 
  create_nodes_and_edges(rxnorm_relationships) %>% 
  add_tooltip() %>% 
  map_node_attributes() %>% 
  map_edge_attributes() %>% 
  construct_graph()
```

```{r}
chariotViz(rxnorm_graph,
           width = 1000,
           height = 1000)
```


```{r}
rxnorm_graph2 <- 
  rxnorm_graph %>% 
  remap_fillcolor_by_concept_class()

chariotViz(rxnorm_graph2,
           width = 1000,
           height = 1000)
```
